### ISSUE TITLE
O bot tuíta aos Sábados e Domingos

### ISSUE THREAD

**Issue by laps15** [Fernando-Erd/rupolitecnico#2]
Nunca existe cardápio para sábado e domingo o que resulta em um tuíte dizendo que o cardapio não foi atualizado.

**Comment by Fernando-Erd** [comment]
Olá meu caro amigo.

Esse problema é do arquivo crontab,  basta arrumar para que não tuíte ao final de semana.

Além disso, existem RU's que funcionam no final de semana, sendo assim o código irá suportar eles também.
